products:
  - fabric
  - copilot
  - one_lake
experiences:
  - power_bi
  - data_engineering
  - data_factory
  - data_science
  - data_warehouse
  - databases
  - real_time_intelligence
  - industry_solutions